# This is a basic workflow to help you get started with Actions

name: automation
on:
  repository_dispatch:
   types: [update]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      env:
         SUPER_SECRET: ${{ secrets.SuperSecret }}
    - name: run converter
      run: |
        mkdir -p instructions/${{ github.event.client_payload.repository }}/
        rm -f instructions/${{ github.event.client_payload.repository }}/README.md
        javac GuideConverter.java
        java GuideConverter ${{ github.event.client_payload.repository }}
        cat instructions/${{ github.event.client_payload.repository }}/README.md
    - name: git push
      run: |
        git add .
        git config --global user.email "action@example.com"
        git config --global user.name "action"
        git commit -m "auto"
        git push
